package com.example.savingbuddy.ui.navigation

sealed class Screen(val route: String) {
    data object Dashboard : Screen("dashboard")
    data object Transactions : Screen("transactions")
    data object AddTransaction : Screen("add_transaction")
    data object AddIncome : Screen("add_income")
    data object AddExpense : Screen("add_expense")
    data object AddSaving : Screen("add_saving")
    data object Savings : Screen("savings")
    data object Transfer : Screen("transfer")
    data object Insights : Screen("insights")
    data object Accounts : Screen("accounts")
    data object Budget : Screen("budget")
    data object Recurring : Screen("recurring")
    data object Loan : Screen("loan")
    data object CreditCard : Screen("credit_card")
    data object Life : Screen("life")
    data object AllFunctions : Screen("all_functions")
    data object Settings : Screen("settings")
    data object About : Screen("about")
    data object NetWorth : Screen("net_worth")
    data object Export : Screen("export")
    data object Health : Screen("health")
    data object HealthScore : Screen("health_score")
    data object Achievements : Screen("achievements")
    data object Analytics : Screen("analytics")
    data object WorkCalendar : Screen("work_calendar")
    data object WorkReport : Screen("work_report")
    data object Backup : Screen("backup")
    data object AddSavings : Screen("add_savings")
}